sitename: "RainPot"
baseURL: "/"
languageCode: en-us
title: "RainPot Blog"
author: RainPot

enableEmoji: true
hasCJKLanguage: false
# You can change code highlight theme
pygmentsstyle: "tango"
pygmentscodefences: true

# if you want to add html to your markdown
markup:
  goldmark:
    renderer:
      unsafe: true

# Links of the navbar
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: Articles
      url: /blog/
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Subscribe
      url: https://github.com/RainPot
      weight: 4

# You can add languages!
# do not expect it to work out of the box
# https://gohugo.io/content-management/multilingual/
defaultContentLanguage: en
languages:
  en:
    LanguageName: English
    # contentDir: content/english
  # ru:
  #   LanguageName: русский
  #   # contentDir: content/russian

params:
  sitename: "RainPot Blog"
  # it will produce: copyrights (c) 2022 joe
  copyrights: RainPot
  # path to the favicon directory
  # see ./layouts/_defaults/baseof.html line #30 to line #37
#  faviconpath: "/img/favicon"
  # projects will show in the index page
  # myprojects:
  #   - name: "Totally Awesome Project"
  #     description: "Machine Learning Magic!!!"
  #     url: https://example.com
  #   - name: "Kaslaanka"
  #     description: "The best hugo theme ever!!!"
  #     url: https://github.com/M1cR0xf7/kaslaanka
  # link to more projects
  # show your github repositories as example
  # or create your own page.
  projectsURL: https://example.com

  # a brief about me
  brief_about: <center>不吃夜宵，从我做起 ❤️️</center>

  # articles archive url (default)
  archive: blog

# and don't forget
theme: kaslaanka